import { AuthContext } from "@/context/AuthContext";
import { Manrope, Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import ConfigureAmplifyClientSide from "./amplify-cognito-config";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Contextufy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${inter.variable} antialiased`}>
        <AuthContext>
        <ToastContainer />

          <ConfigureAmplifyClientSide />

          {children}
        </AuthContext>
      </body>
    </html>
  );
}
